dolphin:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: dolphin-takeaway
    username: root
    password: 123456
  huaweiobs:
    endpoint: obs.cn-north-4.myhuaweicloud.com
    access-key-id: ITYG1VUSXQQ7VAK6ISRF
    access-key-secret: kTzCvVP8cB7WXHcrDyX4MvuCMu9GFZBmLT4fuaaK
    bucket-name: dolphin-takeaway
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1