server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${dolphin.datasource.driver-class-name}
      url: jdbc:mysql://${dolphin.datasource.host}:${dolphin.datasource.port}/${dolphin.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${dolphin.datasource.username}
      password: ${dolphin.datasource.password}

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tong.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

dolphin:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: tong
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  huaweiobs:
    endpoint: ${dolphin.huaweiobs.endpoint}
    access-key-id: ${dolphin.huaweiobs.access-key-secret}
    access-key-secret: ${dolphin.huaweiobs.access-key-secret}
    bucket-name: ${dolphin.huaweiobs.bucket-name}
